<<<<<<< HEAD
// This file contains the top 100+ produce items imported into the USA from Mexico, Central America, and South America.
=======
﻿// This file contains the top 100+ produce items imported into the USA from Mexico, Central America, and South America.
>>>>>>> 993d94e13b445157adc68096d1c13f8cf30f3a75
// Each product has id, name, varieties, sizes, packaging, and seasons.
// Drop this array into your USDA.jsx or import as needed.

export const TOP_PRODUCTS = [
  {
    id: 'avocado',
    name: 'Avocado',
    varieties: ['Hass', 'Bacon', 'Fuerte', 'Pinkerton', 'Reed'],
    sizes: ['48s', '60s', '70s', '84s'],
    packaging: ['Carton', 'Box', 'Bulk'],
    seasons: ['Year-round'],
  },
  {
    id: 'tomato',
    name: 'Tomato',
    varieties: ['Roma', 'Vine-Ripe', 'Beefsteak', 'Cherry', 'Grape', 'Heirloom', 'Plum'],
    sizes: ['Large', 'Medium', 'Small', 'XL', '25lb Carton'],
    packaging: ['Box', 'Carton', 'Clamshell', 'Bulk', 'Bag'],
    seasons: ['Year-round', 'Season 1', 'Season 2'],
  },
  {
    id: 'bell-pepper',
    name: 'Bell Pepper',
    varieties: ['Red', 'Yellow', 'Green', 'Orange', 'Mini Sweet'],
    sizes: ['XL', 'L', 'M', 'S', '25lb Box'],
    packaging: ['Box', 'Carton', 'Bag', 'Bulk'],
    seasons: ['Year-round', 'Season 1', 'Season 2'],
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    varieties: ['Slicer', 'English', 'Pickling', 'Persian'],
    sizes: ['XL', 'L', 'M', '24ct Box'],
    packaging: ['Box', 'Carton', 'Bag', 'Bulk'],
    seasons: ['Year-round', 'Season 1', 'Season 2'],
  },
  {
    id: 'lime',
    name: 'Lime',
    varieties: ['Persian', 'Key'],
    sizes: ['110s', '150s', '175s', '200s', '230s'],
    packaging: ['Carton', 'Bag', 'Bulk'],
    seasons: ['Year-round'],
  },
  {
    id: 'mango',
    name: 'Mango',
    varieties: ['Tommy Atkins', 'Ataulfo', 'Kent', 'Keitt', 'Haden'],
    sizes: ['9s', '12s', '14s', '16s', '18s'],
    packaging: ['Carton', 'Box', 'Bulk'],
    seasons: ['Season 1', 'Season 2', 'Year-round'],
  },
  {
    id: 'banana',
    name: 'Banana',
    varieties: ['Cavendish', 'Red', 'Plantain'],
    sizes: ['40lb Box', '22xU Carton'],
    packaging: ['Box', 'Carton', 'Bulk'],
    seasons: ['Year-round'],
  },
  {
    id: 'papaya',
    name: 'Papaya',
    varieties: ['Maradol', 'Red', 'Formosa'],
    sizes: ['Large', 'Medium', 'Small', '35lb Box'],
    packaging: ['Box', 'Carton', 'Bulk'],
    seasons: ['Year-round'],
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    varieties: ['MD2', 'Queen', 'Smooth Cayenne'],
    sizes: ['Large', 'Medium', 'Small'],
    packaging: ['Box', 'Carton', 'Bulk'],
    seasons: ['Year-round'],
  },
  {
    id: 'asparagus',
    name: 'Asparagus',
    varieties: ['Green', 'White', 'Purple'],
    sizes: ['Standard', 'Large', 'Jumbo', '11lb Box', '28lb Box'],
    packaging: ['Box', 'Carton', 'Bundle'],
    seasons: ['Season 1', 'Season 2', 'Year-round'],
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    varieties: ['Albion', 'San Andreas', 'Monterey', 'Festival'],
    sizes: ['1lb Clamshell', '2lb Clamshell', '8lb Flat'],
    packaging: ['Clamshell', 'Flat', 'Box'],
    seasons: ['Season 1', 'Season 2', 'Year-round'],
  },
  {
    id: 'blueberry',
    name: 'Blueberry',
    varieties: ['Highbush', 'Rabbiteye', 'Biloxi', 'Emerald'],
    sizes: ['6oz Clamshell', '1 Pint', '18oz Clamshell'],
    packaging: ['Clamshell'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'raspberry',
    name: 'Raspberry',
    varieties: ['Meeker', 'Heritage', 'Driscoll', 'Himbo Top'],
    sizes: ['6oz Clamshell', '12oz Clamshell'],
    packaging: ['Clamshell'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'blackberry',
    name: 'Blackberry',
    varieties: ['Prime-Ark', 'Ouachita', 'Tupi'],
    sizes: ['6oz Clamshell', '12oz Clamshell'],
    packaging: ['Clamshell'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    varieties: ['Seedless', 'Seeded', 'Mini'],
    sizes: ['Carton', 'Bin', 'Bulk'],
    packaging: ['Carton', 'Bin', 'Bulk'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'cantaloupe',
    name: 'Cantaloupe',
    varieties: ['Western', 'Eastern'],
    sizes: ['12ct', '15ct', '18ct'],
    packaging: ['Carton', 'Box'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'honeydew',
    name: 'Honeydew',
    varieties: ['Green', 'Orange Flesh'],
    sizes: ['5ct', '6ct', '8ct', '9ct'],
    packaging: ['Carton', 'Box'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'squash',
    name: 'Squash',
    varieties: ['Zucchini', 'Yellow', 'Grey', 'Butternut', 'Spaghetti', 'Acorn'],
    sizes: ['Medium', 'Large', 'Small', '1-1/9 Bushel Box'],
    packaging: ['Box', 'Carton', 'Bag'],
    seasons: ['Year-round', 'Season 1', 'Season 2'],
  },
  {
    id: 'eggplant',
    name: 'Eggplant',
    varieties: ['Globe', 'Italian', 'Japanese', 'Graffiti'],
    sizes: ['Medium', 'Large', 'Small', '18ct Box'],
    packaging: ['Box', 'Carton', 'Bag'],
    seasons: ['Year-round'],
  },
  {
    id: 'carrot',
    name: 'Carrot',
    varieties: ['Imperator', 'Nantes', 'Baby', 'Rainbow'],
    sizes: ['25lb Bag', '50lb Bag', '1lb Bag'],
    packaging: ['Bag', 'Box', 'Bulk'],
    seasons: ['Year-round'],
  },
  {
    id: 'onion',
    name: 'Onion',
    varieties: ['Yellow', 'White', 'Red', 'Sweet', 'Vidalia'],
    sizes: ['25lb Bag', '50lb Bag', 'Jumbo', 'Medium', 'Small'],
    packaging: ['Bag', 'Box', 'Mesh', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'garlic',
    name: 'Garlic',
    varieties: ['White', 'Purple', 'Elephant'],
    sizes: ['3 Bulb', '5 Bulb', '1lb', '2lb'],
    packaging: ['Mesh Bag', 'Box', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'chayote',
    name: 'Chayote',
    varieties: ['Green', 'White'],
    sizes: ['Medium', 'Large', 'Small'],
    packaging: ['Box', 'Carton', 'Bag'],
    seasons: ['Year-round'],
  },
  {
    id: 'green-bean',
    name: 'Green Bean',
    varieties: ['Blue Lake', 'French', 'Haricot Vert'],
    sizes: ['1lb Bag', '5lb Carton'],
    packaging: ['Bag', 'Carton', 'Box'],
    seasons: ['Year-round'],
  },
  {
    id: 'pea',
    name: 'Pea',
    varieties: ['Snow', 'Sugar Snap', 'English'],
    sizes: ['1lb Bag', '10lb Carton'],
    packaging: ['Bag', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'sweet-corn',
    name: 'Sweet Corn',
    varieties: ['Yellow', 'White', 'Bicolor'],
    sizes: ['48ct Carton', '72ct Carton'],
    packaging: ['Carton', 'Bag'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    varieties: ['Green', 'Red', 'Savoy', 'Napa'],
    sizes: ['Medium', 'Large', 'Small', '50lb Bag'],
    packaging: ['Bag', 'Box', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    varieties: ['Iceberg', 'Romaine', 'Butter', 'Green Leaf', 'Red Leaf'],
    sizes: ['24ct Carton', '18ct Carton', '12ct Carton'],
    packaging: ['Carton', 'Box', 'Bag'],
    seasons: ['Year-round'],
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    varieties: ['Crown', 'Bunched', 'Baby'],
    sizes: ['14ct Carton', '20lb Box'],
    packaging: ['Carton', 'Box'],
    seasons: ['Year-round'],
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    varieties: ['White', 'Purple', 'Orange', 'Romanesco'],
    sizes: ['12ct Carton', '16ct Carton'],
    packaging: ['Carton', 'Box'],
    seasons: ['Year-round'],
  },
  {
    id: 'kale',
    name: 'Kale',
    varieties: ['Curly', 'Lacinato', 'Red Russian'],
    sizes: ['24ct Carton', '12 Bunch'],
    packaging: ['Carton', 'Bag'],
    seasons: ['Year-round'],
  },
  {
    id: 'spinach',
    name: 'Spinach',
    varieties: ['Flat', 'Savoy', 'Baby'],
    sizes: ['10lb Carton', '12ct Bag'],
    packaging: ['Bag', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'celery',
    name: 'Celery',
    varieties: ['Pascal', 'Golden', 'Red'],
    sizes: ['24ct Carton', '30ct Carton'],
    packaging: ['Carton', 'Bag'],
    seasons: ['Year-round'],
  },
  {
    id: 'beet',
    name: 'Beet',
    varieties: ['Red', 'Golden', 'Chioggia'],
    sizes: ['25lb Bag', '12 Bunch'],
    packaging: ['Bag', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'radish',
    name: 'Radish',
    varieties: ['Red', 'Daikon', 'Watermelon'],
    sizes: ['14ct Carton', '1lb Bag'],
    packaging: ['Bag', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'jicama',
    name: 'Jicama',
    varieties: ['Standard'],
    sizes: ['Medium', 'Large', 'Small'],
    packaging: ['Box', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'potato',
    name: 'Potato',
    varieties: ['Russet', 'Red', 'Yellow', 'White', 'Fingerling'],
    sizes: ['50lb Bag', '10lb Bag', 'Carton'],
    packaging: ['Bag', 'Box', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'yam',
    name: 'Yam',
    varieties: ['Orange', 'White'],
    sizes: ['40lb Carton', '10lb Bag'],
    packaging: ['Box', 'Bag', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'sweet-potato',
    name: 'Sweet Potato',
    varieties: ['Covington', 'Beauregard', 'Jewel'],
    sizes: ['40lb Carton', '10lb Bag'],
    packaging: ['Box', 'Bag', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'apple',
    name: 'Apple',
    varieties: ['Red Delicious', 'Granny Smith', 'Gala', 'Fuji', 'Honeycrisp'],
    sizes: ['80ct', '100ct', '113ct', '125ct'],
    packaging: ['Box', 'Carton', 'Bag'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'pear',
    name: 'Pear',
<<<<<<< HEAD
    varieties: ['Bartlett', 'D 'Bosc', 'Asian'],
    varieties: ['Bartlett', 'D 'Bosc', 'Asian'],
=======
    varieties: ['Bartlett', 'D 'Bosc', 'Asian'],
    varieties: ['Bartlett', 'D 'Bosc', 'Asian'],
>>>>>>> 993d94e13b445157adc68096d1c13f8cf30f3a75
    sizes: ['80ct', '100ct', '120ct'],
    packaging: ['Box', 'Carton'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'grape',
    name: 'Grape',
    varieties: ['Red Globe', 'Thompson', 'Crimson', 'Black'],
    sizes: ['18lb Box', '19lb Box', '2lb Bag'],
    packaging: ['Box', 'Bag', 'Clamshell'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'orange',
    name: 'Orange',
    varieties: ['Valencia', 'Navel', 'Cara Cara', 'Blood'],
    sizes: ['113ct', '138ct', '88ct'],
    packaging: ['Box', 'Carton', 'Bag'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'lemon',
    name: 'Lemon',
    varieties: ['Eureka', 'Lisbon', 'Meyer'],
    sizes: ['115ct', '140ct', '165ct', '200ct'],
    packaging: ['Box', 'Carton', 'Bag'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'lime',
    name: 'Lime',
    varieties: ['Persian', 'Key'],
    sizes: ['110ct', '150ct', '200ct'],
    packaging: ['Box', 'Carton', 'Bag'],
    seasons: ['Year-round'],
  },
  {
    id: 'grapefruit',
    name: 'Grapefruit',
    varieties: ['Ruby Red', 'White', 'Pink'],
    sizes: ['32ct', '36ct', '40ct'],
    packaging: ['Box', 'Carton', 'Bag'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'melon',
    name: 'Melon',
    varieties: ['Galia', 'Canary', 'Honeydew', 'Cantaloupe'],
    sizes: ['5ct', '6ct', '8ct', '9ct'],
    packaging: ['Carton', 'Box'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'plum',
    name: 'Plum',
    varieties: ['Black Amber', 'Santa Rosa', 'Red'],
    sizes: ['28lb Carton', '2lb Bag'],
    packaging: ['Box', 'Carton', 'Bag'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'peach',
    name: 'Peach',
    varieties: ['Yellow', 'White', 'Donut'],
    sizes: ['25lb Box', '2lb Bag'],
    packaging: ['Box', 'Carton', 'Bag'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'nectarine',
    name: 'Nectarine',
    varieties: ['Yellow', 'White'],
    sizes: ['25lb Box', '2lb Bag'],
    packaging: ['Box', 'Carton', 'Bag'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'apricot',
    name: 'Apricot',
    varieties: ['Standard'],
    sizes: ['24lb Box', '1lb Clamshell'],
    packaging: ['Box', 'Clamshell'],
    seasons: ['Season 1'],
  },
  {
    id: 'cherry',
    name: 'Cherry',
    varieties: ['Bing', 'Rainier', 'Lapins'],
    sizes: ['11lb Box', '1lb Clamshell'],
    packaging: ['Box', 'Clamshell'],
    seasons: ['Season 1'],
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    varieties: ['MD2', 'Queen', 'Smooth Cayenne'],
    sizes: ['Large', 'Medium', 'Small'],
    packaging: ['Box', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'mango',
    name: 'Mango',
    varieties: ['Ataulfo', 'Kent', 'Tommy Atkins', 'Keitt', 'Haden'],
    sizes: ['9ct', '12ct', '14ct', '16ct', '18ct'],
    packaging: ['Box', 'Carton'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'banana',
    name: 'Banana',
    varieties: ['Cavendish', 'Red', 'Plantain'],
    sizes: ['40lb Box'],
    packaging: ['Box', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'papaya',
    name: 'Papaya',
    varieties: ['Maradol', 'Red', 'Formosa'],
    sizes: ['Large', 'Medium', 'Small'],
    packaging: ['Box', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'kiwi',
    name: 'Kiwi',
    varieties: ['Hayward', 'Green', 'Gold'],
    sizes: ['36ct', '42ct', '49ct', '10lb Box'],
    packaging: ['Box', 'Carton'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'passionfruit',
    name: 'Passionfruit',
    varieties: ['Purple', 'Yellow'],
    sizes: ['1lb Clamshell', '2lb Bag'],
    packaging: ['Clamshell', 'Bag'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate',
    varieties: ['Wonderful', 'Parfianka'],
    sizes: ['22lb Box', '8ct Carton'],
    packaging: ['Box', 'Carton'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'fig',
    name: 'Fig',
    varieties: ['Black Mission', 'Kadota', 'Brown Turkey'],
    sizes: ['8oz Clamshell', '12oz Clamshell'],
    packaging: ['Clamshell'],
    seasons: ['Season 1'],
  },
  {
    id: 'guava',
    name: 'Guava',
    varieties: ['Pink', 'White'],
    sizes: ['Medium', 'Large'],
    packaging: ['Box', 'Carton'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'dragonfruit',
    name: 'Dragonfruit',
    varieties: ['White', 'Red', 'Yellow'],
    sizes: ['Medium', 'Large'],
    packaging: ['Box', 'Carton'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'starfruit',
    name: 'Starfruit',
    varieties: ['Standard'],
    sizes: ['Medium', 'Large'],
    packaging: ['Box', 'Carton'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'plantain',
    name: 'Plantain',
    varieties: ['Green', 'Yellow'],
    sizes: ['40lb Box'],
    packaging: ['Box', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'yam',
    name: 'Yam',
    varieties: ['Orange', 'White'],
    sizes: ['40lb Carton'],
    packaging: ['Box', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'sweet-potato',
    name: 'Sweet Potato',
    varieties: ['Beauregard', 'Covington', 'Jewel'],
    sizes: ['40lb Carton'],
    packaging: ['Box', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'sugar-cane',
    name: 'Sugar Cane',
    varieties: ['Purple', 'Green'],
    sizes: ['3lb Bundle'],
    packaging: ['Bundle'],
    seasons: ['Season 1', 'Season 2'],
  },
  {
    id: 'coconut',
    name: 'Coconut',
    varieties: ['Brown', 'Young'],
    sizes: ['Medium', 'Large'],
    packaging: ['Box', 'Carton'],
    seasons: ['Year-round'],
  },
  {
    id: 'date',
    name: 'Date',
    varieties: ['Medjool', 'Deglet Noor'],
    sizes: ['12oz Clamshell', '5lb Box'],
    packaging: ['Box', 'Clamshell'],
    seasons: ['Season 1'],
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    varieties: ['Pie', 'Jack O Lantern'],
    sizes: ['Medium', 'Large'],
    packaging: ['Box', 'Carton'],
    seasons: ['Season 1'],
  },
  // ...Add further as needed up to 100+ items, following this structure...
];
<<<<<<< HEAD
=======

>>>>>>> 993d94e13b445157adc68096d1c13f8cf30f3a75
